CREATE TABLE venda(
    id SERIAL NOT NULL PRIMARY KEY,
    data_hora TIMESTAMP NOT NULL,
    usuario_id VARCHAR(255) NOT NULL
);

ALTER TABLE venda ADD CONSTRAINT FK_USUARIO_ID FOREIGN KEY (usuario_id) REFERENCES usuario (id);